---
# file: tasks/install-git-tools.yml
# Top-level installer tools required for compiling Prometheus sources.
#
# @see https://github.com/prometheus/prometheus
#

- name: install dependencies for installation of components from source
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
  with_items:
    - git
    - gzip
    - curl
    - gcc

- name: install make
  yum: name=make state=present update_cache=yes
  when: ansible_pkg_mgr == "yum"

- name: install make
  apt: name=build-essential state=present update_cache=yes
  when: ansible_pkg_mgr == "apt"


- name: set internal variables for convenience
  set_fact:
    prometheus_golang_tarball_url: "https://storage.googleapis.com/golang/go{{ prometheus_go_version }}.linux-amd64.tar.gz"
    #prometheus_golang_tarball_url: "http://golang.org/dl/go{{ prometheus_go_version }}.linux-amd64.tar.gz"
  when: ansible_userspace_bits == "64"

- name: set internal variables for convenience
  set_fact:
    prometheus_golang_tarball_url: "https://storage.googleapis.com/golang/go{{ prometheus_go_version }}.linux-386.tar.gz"
    #prometheus_golang_tarball_url: "http://golang.org/dl/go{{ prometheus_go_version }}.linux-386.tar.gz"
  when: ansible_userspace_bits == "32"

- name: mkdir for Golang
  file: path={{ item }}  state=directory
  with_items:
    - "{{ prometheus_goroot }}"
    - "{{ prometheus_gopath }}"

- name: download and untar Golang tarball
  unarchive:
    src:  "{{ prometheus_golang_tarball_url }}"
    dest: "{{ prometheus_workdir }}"
    copy: no
    creates: "{{ prometheus_goroot }}/bin/go"
