---
# file: tasks/install-consul-exporter.yml
#
# Install Prometheus consul-exporter.
#
# @see http://prometheus.io/docs/introduction/getting_started/
#


- name: set internal variables for convenience
  set_fact:
    prometheus_consul_exporter_tarball_url: "https://github.com/prometheus/consul_exporter/releases/download/{{ prometheus_consul_exporter_version }}/consul_exporter-{{ prometheus_consul_exporter_version }}.linux-amd64.tar.gz"
    prometheus_untar_path: "{{ prometheus_install_path }}"
  when: prometheus_consul_exporter_version != "git" and ansible_userspace_bits == "64"

- name: set internal variables for convenience
  set_fact:
    prometheus_consul_exporter_tarball_url: "https://github.com/prometheus/consul_exporter/releases/download/{{ prometheus_consul_exporter_version }}/consul_exporter-{{ prometheus_consul_exporter_version }}.linux-386.tar.gz"
    prometheus_untar_path: "{{ prometheus_install_path }}"
  when: prometheus_consul_exporter_version != "git" and ansible_userspace_bits == "32"

- name: set internal variables for convenience
  set_fact:
    prometheus_consul_exporter_tarball_url: "https://github.com/prometheus/consul_exporter/archive/master.tar.gz"
    prometheus_untar_path: "{{ prometheus_download_path }}"
  when: prometheus_consul_exporter_version == "git"

- name: delete the consul_exporter directory if it already exists
  file: path="{{ prometheus_download_path }}/consul_exporter-master" state=absent
  when: prometheus_consul_exporter_version == "git"

- name: download consul_exporter tarball
  get_url: url="{{ prometheus_consul_exporter_tarball_url }}"  dest="{{ prometheus_download_path }}/consul_exporter.tar.gz"

- name: untar consul_exporter tarball
  unarchive:
    src: "{{ prometheus_download_path }}/consul_exporter.tar.gz"
    dest: "{{ prometheus_untar_path }}"
    copy: no

- name: build consul_exporter
  command: make
  args:
    chdir: "{{ prometheus_download_path }}/consul_exporter-master"
    creates: consul_exporter
  when: prometheus_consul_exporter_version == "git"

- name: move the built consul_exporter to the install path
  command: "mv {{ prometheus_download_path }}/consul_exporter-master/consul_exporter {{ prometheus_install_path }}"
  when: prometheus_consul_exporter_version == "git"

- name: set permissions, owner and group
  file: path={{ prometheus_install_path }}/consul_exporter owner={{ prometheus_user }} group={{ prometheus_group }} mode="go-w"


- name: set consul_exporter variables
  copy: src="../files/etc-default-consul_exporter"  dest=/etc/default/consul_exporter

- name: copy INIT script to server
  template: src="../templates/consul_exporter.sysvinit.{{ ansible_os_family|lower }}.sh.j2"  dest="/etc/init.d/consul_exporter"  mode="a+x"

- name: set INIT status
  service: name=consul_exporter enabled=yes state=started
