global:

route:
  group_by: ['alertname', 'cluster']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  continue: true
  receiver: 'default-pager'


receivers:
  - name: 'default-pager'
    pagerduty_configs:
    - service_key: <team-X-key>